//! Runtime support for Rust code generated by `humblegen`.
//!
//! The module-level comments of this crate are prefixed to give guidance from where they are used:
//! - `GEN` = used by generated code
//! - `PROTO` = part of the de-facto HTTP protocol between server and client
//! - `SERVER` = within the `server` module
//! - `HANDLER` = from the handler implementation

pub mod serialization_helpers;
pub use serialization_helpers as deser_helpers; // compat
pub mod handler;
pub mod regexset_map;
pub mod server;
pub mod service_protocol;

pub extern crate anyhow;
pub extern crate chrono;
pub extern crate downcast_rs;
pub extern crate hyper;
pub extern crate regex;
pub extern crate tokio;
pub extern crate tracing;
pub extern crate uuid;

pub use async_trait_with_sync::async_trait;
